# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('curriculum_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Curricula ID')),
                ('semester_system_type', models.CharField(choices=[('S', 'Semester'), ('T', 'Trimester')], max_length=1, verbose_name='Semester System Type')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.Department', verbose_name='Department')),
            ],
        ),
    ]
