# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50, verbose_name='Department Name')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculties.Faculty', verbose_name='Faculty')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=set([('faculty', 'department_name')]),
        ),
    ]
