-- DROP TABLE Student;

CREATE TABLE IF NOT EXISTS Students(
    sid INT(10) NOT NULL AUTO_INCREMENT NOT NULL,
    student_id CHAR(10) NOT NULL,
    curid INT(10) NOT NULL,
    memid INT(10) NOT NULL,
    title VARCHAR(20) NOT NULL,
    firstname VARCHAR(50) NOT NULL,
    lastname VARCHAR(50) NOT NULL,
    email VARCHAR(30),
    nationality VARCHAR(30),
    birthdate DATE,
    gender VARCHAR(10) NOT NULL,
    citizen_id VARCHAR(15) NOT NULL,
    religion VARCHAR(20),
    mobile VARCHAR(15),
    img VARCHAR(40),
    addr VARCHAR(50),
    province VARCHAR(20),
    zipcode VARCHAR(10),
    country VARCHAR(20),
    emer_name VARCHAR(20),
    emer_mobile VARCHAR(15),
    emer_addr VARCHAR(50),
    emer_province VARCHAR(20),
    emer_zipcode VARCHAR(10),
    emer_country VARCHAR(20),
    highschool_name VARCHAR(50),
    highschool_grade VARCHAR(5),
    gpax REAL,
    semester_count INT(2) NOT NULL,
    summer_count INT(2) NOT NULL,
    status CHAR(1) NOT NULL,
    behavioral_score INT(3) NOT NULL,
    PRIMARY KEY (sid)
);

INSERT INTO Students(
    student_id,
    curid,
    memid,
    title,
    firstname,
    lastname,
    email,
    nationality,
    birthdate,
    gender,
    citizen_id,
    religion,
    mobile,
    img,
    addr,
    province,
    zipcode,
    country,
    emer_name,
    emer_mobile,
    emer_addr,
    emer_province,
    emer_zipcode,
    emer_country,
    highschool_name,
    highschool_grade,
    gpax,
    semester_count,
    summer_count,
    status,
    behavioral_score
) VALUES (
    5730342321,
    1,
    1,
    'Mr.',
    'Thanat',
    'Jathuphattarachat',
    'thanat.j@gmail.com',
    'Thai',
    '1995-01-23',
    'Male',
    '1659392938225',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    4.00,
    4,
    1,
    'd',
    100
);

INSERT INTO Students(
    student_id,
    curid,
    memid,
    title,
    firstname,
    lastname,
    email,
    nationality,
    birthdate,
    gender,
    citizen_id,
    religion,
    mobile,
    img,
    addr,
    province,
    zipcode,
    country,
    emer_name,
    emer_mobile,
    emer_addr,
    emer_province,
    emer_zipcode,
    emer_country,
    highschool_name,
    highschool_grade,
    gpax,
    semester_count,
    summer_count,
    status,
    behavioral_score
) VALUES (
    5730635521,
    1,
    10,
    'Ms.',
    'Sirinthra',
    'Chantharaj',
    'sirinthra.c@gmail.com',
    'Thai',
    '1996-05-04',
    'Female',
    '1659245382254',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    3.80,
    5,
    0,
    'c',
    100
);

INSERT INTO Students(
    student_id,
    curid,
    memid,
    title,
    firstname,
    lastname,
    email,
    nationality,
    birthdate,
    gender,
    citizen_id,
    religion,
    mobile,
    img,
    addr,
    province,
    zipcode,
    country,
    emer_name,
    emer_mobile,
    emer_addr,
    emer_province,
    emer_zipcode,
    emer_country,
    highschool_name,
    highschool_grade,
    gpax,
    semester_count,
    summer_count,
    status,
    behavioral_score
) VALUES (
    5730342921,
    1,
    4,
    'Mr.',
    'Parinthorn',
    'Saithong',
    'parinthorn.s@gmail.com',
    'Thai',
    '1996-06-20',
    'Male',
    '1657532938259',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    3.95,
    5,
    1,
    'd',
    100
);

SELECT * FROM Students