# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('fid', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Faculty ID')),
                ('name', models.CharField(max_length=50, verbose_name='Faculty Name')),
            ],
        ),
    ]
