# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Faculty ID')),
                ('faculty_name', models.CharField(max_length=50, verbose_name='Faculty Name')),
            ],
        ),
    ]
